
apiVersion: v1
kind: Service
metadata:
  name: truck-data-api-svc
spec:
  type: ClusterIP
  selector:
    app: truck-data-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-data-api
  name: truck-data-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-data-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-data-api
    spec:
      containers:
      - image: jlnhnng/truck-python-api:latest
        imagePullPolicy: Always
        name: truck-data-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CURRENT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KAFKA
          value: "kafka-kafka-0.kafka-svc.projectone-gsj48.svc.cluster.local:9093"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: truck-data-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /data-api
        backend:
          serviceName: truck-data-api-svc
          servicePort: 8080