
apiVersion: v1
kind: Service
metadata:
  name: truck-demo-ui-svc
spec:
  type: Loadbalancer
  selector:
    app: truck-demo-ui
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-demo-ui
  name: truck-demo-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-demo-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-demo-ui
    spec:
      containers:
      - image: d2iqdemo/truck-demo-ui:latest
        imagePullPolicy: Always
        name: truck-demo-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CURRENT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: API_URL
          value: "http://truck-data-connector"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}