apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-data-connector
  name: truck-data-connector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-data-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-data-connector
    spec:
      containers:
      - image: jlnhnng/truck-data-connector:latest
        imagePullPolicy: Always
        name: truck-data-connector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: Kafka
          value: kafka-kafka-0.kafka-svc.default.svc.cluster.local:9093
        - name: Topic
          value: 'trucks' 
        - name: Cassandra
          value: cassandra-node-0.cassandra-svc.default.svc.cluster.local:9042
      initContainers:
      - image: jlnhnng/truck-cassandra-init:latest
        imagePullPolicy: Always
        name: cassandra-init
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: truck-data-connector-svc
spec:
  selector:
    app: truck-data-connector
  ports:
    - port: 3002
      targetPort: 3002
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: truck-data-connector-ingress
spec:
  rules:
  - http:
      paths:
      - path: /data-connector
        backend:
          serviceName: truck-data-connector-svc
          servicePort: 3002