---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mirantis-labs
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./mirantis-labs/gitops/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mirantis-labs

